### ISSUE TITLE
configure tutorial 

### ISSUE THREAD

**Issue by magj2006** [pontem-network/pontem-wallet#1]
**Is your feature request related to a problem? Please describe.**
I want to use BTC and USDT from your platform, but I don't know how to add it in move.toml config file,  I added it same as below, but it's not working.

<img width="841" alt="截屏2022-08-19 11 11 02" src="https://user-images.githubusercontent.com/8394789/185534647-efc58793-b314-4512-88be-f52727973be8.png">

**Comment by borispovod** [comment]
Hey,

You can read in our docs - https://docs.liquidswap.com/integration
