### ISSUE TITLE
[Feature] Add ability to rename addresses

### ISSUE THREAD

**Issue by dylanschultzie** [pontem-network/pontem-wallet#4]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Rather than just having "Account 2", you should be able to rename your wallets.

<img width="166" alt="Screen Shot 2022-10-20 at 12 54 21 PM" src="https://user-images.githubusercontent.com/9121234/197011086-979c648d-53b9-462b-81ed-46681966a491.png">

Perhaps under account details?
<img width="292" alt="Screen Shot 2022-10-20 at 12 55 07 PM" src="https://user-images.githubusercontent.com/9121234/197011336-21cf32a0-6220-4371-b5f1-5910f142e609.png">

**Comment by QA-Dmitriy** [comment]
Hello sir!
Thank you for your attentiveness, this task is in our backlog, we will move on to it according to priorities

**Comment by DmitriyKing** [comment]
Request completed
Thank you for your participation!
