### ISSUE TITLE
[Feature] Add functionality for saving addresses

### ISSUE THREAD

**Issue by dylanschultzie** [pontem-network/pontem-wallet#5]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
When sending or interacting with an address, you should be able to save the address for later:
<img width="388" alt="Screen Shot 2022-10-20 at 12 56 13 PM" src="https://user-images.githubusercontent.com/9121234/197011543-d1676d7b-7339-4859-a151-662e475a893e.png">

**Comment by QA-Dmitriy** [comment]
Hello sir!
Thank you for your attentiveness again, this task is in our backlog too, we will move on to it according to priorities

**Comment by DmitriyKing** [comment]
Request completed
Thank you for your participation!
