### ISSUE TITLE
[Feature] Interact with addresses via aptos name server

### ISSUE THREAD

**Issue by dylanschultzie** [pontem-network/pontem-wallet#6]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Identity is important in crypto, and having a built in naming system like Aptos does goes a long way to simplify the user experience. 
<img width="372" alt="Screen Shot 2022-10-20 at 12 57 53 PM" src="https://user-images.githubusercontent.com/9121234/197011882-03fd6ce0-cec2-4ab9-9532-d8d2d213696a.png">

Petra wallet:
<img width="287" alt="Screen Shot 2022-10-20 at 12 58 10 PM" src="https://user-images.githubusercontent.com/9121234/197011942-fbd09034-37c7-40ea-9b6b-c0f6c9e12a73.png">

**Comment by QA-Dmitriy** [comment]
Hello, sir!
Our team will discussed this feature request, thxs

**Comment by QA-Dmitriy** [comment]
We will add this feature to our backlog and dev it by priorities

**Comment by dylanschultzie** [comment]
Thanks @QA-Dmitriy - should I close my 3 issues?

**Comment by DmitriyKing** [comment]
You're welcome
I will close them. Now, discussions and improvements are still underway on the part of the requested functionality, but in general, we have already tried to close them at least at a minimum level.
