### ISSUE TITLE
I can't import seed phrase from web interface

### ISSUE THREAD

**Issue by nickhopes** [pontem-network/pontem-wallet#8]
**Describe the bug**
I can't import seed phrase from web interface. The "import" bottom isn't worked

**To Reproduce**
1. Install wallet → *redirected to web interface
2. Click on 'import wallet (import an existing wallet)'
3. Paste phrase → Write password 
4. Click on "import" → no anything happen

**Expected behavior**
Click on "import" → import is done OR error massage

**Screenshots**
https://drive.google.com/drive/folders/1FotSkmQHZEfp3qZnF7JQi8S1J7P0JquQ?usp=sharing

**Desktop (please complete the following information):**
 - OS: MacOs Monteray 12.6
 - Browser Chrome
 - Version 106.0.5249.119 (Official Build) (arm64)

**Comment by QA-Dmitriy** [comment]
Hello, sir!
Thank you for your care, we have fixed this bug.
