### ISSUE TITLE
An APTOS Name V1 NFT display BUG 

### ISSUE THREAD

**Issue by ssing2088** [pontem-network/pontem-wallet#9]
**Describe the bug**
1. I have one APTOS name danone.apt ;
2. In my wallet , it shows three times !

My Wallet: 0xe393cd829284e374e98d61d0d2a9c20bce84313faa7b3e9bc79524d5f37f5d98 

**To Reproduce**
It's alwayes there.

**Expected behavior**
It's alwayes there. 

**Screenshots**
https://gateway.pinata.cloud/ipfs/QmXkii8R5F34fbCApb4YApeGFYurMtDYCfhEao7SXtjecw 

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version [版本 107.0.5304.10（正式版本） （64 位)

**Additional context**

**Comment by QA-Dmitriy** [comment]
Hello, sir!
Thank you for your attention to detail, we know about this bug and it is one of the priorities, soon you will be able to see its correction in the application

**Comment by ssing2088** [comment]
It's fixed! Thanks for your quick response !

**Comment by QA-Dmitriy** [comment]
Welcome, sir
